### PR TITLE
Feature/release refactoring

### LINKED ISSUE #60: Fix all for publishing component library
## Bug Report

**Current behavior & Fixes**
- [x] Replace Wikipedia SVG with correct file
- [x] Remove GDPR pdf from img folder
- [x] Create local exportable script for testing before publishing to NPM.
- [x] Export all correct folder from src/* to dist folder. Rollup config.
- [x] Organize type file into single folder.
- [x] Update the README with up to date information for above.
- [x] Create minified package for publishing to NPM.
- [x] Create visualization of packages similar to below with new structure.

**Screenshots**
Screenshot 2022-09-07 at 14 38 24

### PR DESCRIPTION
**Pull request by withchristopher**
## Related issue

Closes #60 

## Description

This PR covers the publishable version of the factiverse component library.

There are a multiple ways to publish:
- locally, instructions can be found in the README.md.
- NPM - first choice and can found in README.md.
- Github - second choice and can found in README.md.

Refactored: 
- rebased with develop
- Rollup config file
- README
- package.json
- Statically assigned version, this component should not be used in prod. Will need to be addressed in new issue.
- Created a `npm generate` to create new components automatically. 
- Updated the CI to install all packages to pass tests.
- Updated GH action versions:
  - actions/checkout@v2 -> v3
  - actions/cache@v2 -> v3
  - actions/setup-node@v2 -> v3

## Screenshots (before and after the change):

Rollup Visualizer:
Screenshot 2022-09-12 at 16 02 06

### CODE REVIEW

**Review by DomyS — COMMENTED** [review]
Seems like you did a lot of great work! 
I think the only question I have is why we have some stories written in MDX and some with TSX.

And it looks like some storybook tests are failing, but in general I would approve this PR.

**Comment by withchristopher** [comment]
Thanks @DomyS. The tests are failing since the enum type definition in the MicrofactsArticle and MicrofactsTooltip as shown below, is not being read.
Screenshot 2022-09-13 at 09 07 52

**Comment by DomyS** [comment]
> Thanks @DomyS. The tests are failing since the enum type definition in the MicrofactsArticle and MicrofactsTooltip as shown below, is not being read. Screenshot 2022-09-13 at 09 07 52

Hmm, so you can add different type

> Thanks @DomyS. The tests are failing since the enum type definition in the MicrofactsArticle and MicrofactsTooltip as shown below, is not being read. Screenshot 2022-09-13 at 09 07 52

You can add:

`export enum EntityType `

and then to MicrofactsArticle.stories.tsx add:
`import { EntityType } from '../../types';`

Let me know if this will not work.

**Comment by withchristopher** [comment]
@DomyS, there was a bundling error with the path (pretty much the storybook (of-my-life) for the past week has been path errors.

I decided to hardcode the Person value to the storybook. Since this is a story, it is not relevant to the NPM package.

**Review by DomyS — APPROVED** [review]
@withchristopher ah, got it. No worries, I was thinking that maybe we will not able to merge it, if we will have testing errors. Anyways LGTM 👍

**Comment by withchristopher** [comment]
@tobiastykvart , please can you review this before I merge with develop.

**Comment by withchristopher** [comment]
The node.yml GH action should be updated to install peerDependencies for the tests to pass,or equivalent

**Review by tobiastykvart — APPROVED** [review]
LGTM

**Pull request merged**
